made devup and devssh scripts more user friendly by adding help menus

diff --git a/bin/devup b/bin/devup
--- a/bin/devup
+++ b/bin/devup
@@ -4,4 +4,30 @@
 
 set -e
 
-devpod up . --provider docker --dotfiles https://github.com/cjn4825/.dotfiles.git --dotfiles-script scripts/bootstrap.sh --ide none
+INPUT="$1"
+
+MENU="
+Usage: devup [PATH]
+
+Builds container via devop with personalized dotfiles
+
+Examples:
+    devup /path/to/project
+    devup .
+    devup --help
+"
+
+if [[ -z "$INPUT" || "$INPUT" == "--help" ]]; then
+    echo "$MENU"
+    exit 0
+elif [[ -d "$INPUT" ]]; then
+    echo "Building devpod project at: $INPUT"
+    devpod up "$INPUT" \
+        --provider docker \
+        --dotfiles https://github.com/cjn4825/.dotfiles.git \
+        --dotfiles-script scripts/bootstrap.sh \
+        --ide none
+else
+    echo "Error: Path '$INPUT' not found."
+    exit 1
+fi
